# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ad00f6473bd19bf14001ba2cab9bdb0e4e6ec4d27e70c72904371a9acad84972b464f2410dec516e37d5d16f75d7b2b655a5644066598a511eb56058f1d862

test:
  secret_key_base: 63bbf226215ba698700b9978f897b2ab0db64cbd59d1849c6dc512ee3a7441b15bc24c952f2254a4ffe28c8960462e02f6e11f0acc9f631b4c52f18eb6cc478d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


